services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - path: .env.render
        required: true
    depends_on:
      - database
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true
    command: ["postgres", "-c", "log_statement=all"]
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data: