services:
    database:
        image: postgres:alpine
        ports:
            - "5432:5432"
        env_file:
            - path: .env
        command: ["postgres", "-c", "log_statement=all"]
    # redis:
    #     image: redis
    #     container_name: redis
    #     restart: always
    #     ports:
    #         - "6380:6379"
    #     command: ["redis-server", "--requirepass", "my-top-secret"]
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:  
